Sitegeist:
  NeosGuidelines:
    distribution:
      mandatoryFiles:
        'README.md': 'No README.md file in your project root'
        'composer.json': 'No composer.json file in your project root'
        'composer.lock': 'No composer.lock file in your project root'
        '.editorconfig': 'No .editoroconfig file in your project root'
        '.nvmrc': 'No .nvmrc file in your project root'
      readmeFile: 'README.md'
      readmeSections:
        'Installation': 'No headline Installation in your README.md found'
        'Versionskontrolle': 'No headline Versionskontrolle in your README.md found'
        'Deployment': 'No headline Deployment in your README.md found'
    packageDefaults:
      php:
        manifest: 'composer.json'
        lintCommand: 'composer run-script lint'
        additionalFiles: []
      js:
        manifest: 'package.json'
        lintCommand: 'npm run lint'
        additionalFiles: ['npm-shrinkwrap.json']
      editorconfig:
        exclude: ['node_modules', 'Public']
    # packages:
    #   packageKey:
    #     path: 'Packages/Sites/Neos.Demo/'
    #     config:
    #       js:
    #         blabla: 'bbb'
    #       php:
    #         wawawa: 'ccc'
