Sitegeist:
  NeosGuidelines:
    distribution:

      #
      # the validators that are applied to the distribution
      #
      validators:

        MandatoryFiles:
          validator: Sitegeist\NeosGuidelines\Validators\Distribution\MandatoryFilesDistributionValidator
          options:
            files: ['README.md', 'composer.json', 'composer.lock', '.editorconfig']

        ReadmeSections:
          validator: Sitegeist\NeosGuidelines\Validators\Distribution\MarkdownFileDistributionValidator
          options:
            fileName: 'README.md'
            requiredSections: [ 'Installation', 'Versioning', 'Deployment']

        Composer:
          validator: Sitegeist\NeosGuidelines\Validators\Distribution\ComposerFileDistributionValidator
          options:
            requiredSettings:
              - 'config.platform.php'
              - 'scripts.lint'
              - 'scripts.test'

    packages:

      #
      # the list of the packages that should be validated
      # for testing proposes the neos guideline validate themselves
      #
      packageKeys: []

      #
      # the validators that are applied to each package
      #
      validators:
        MandatoryFiles:
          validator: Sitegeist\NeosGuidelines\Validators\Package\MandatoryFilesPackageValidator
          options:
            files: ['composer.json']

        NodeTypes:
          validator: Sitegeist\NeosGuidelines\Validators\Package\NodeTypeValidator
          options:
            allowedNodeTypePrefixes: ['Content', 'Document', 'Mixin', 'Constraint', 'Collection', 'Override']
            abstractNodeTypePrefixes: ['Mixin', 'Constraint']

        Fusion:
          validator: Sitegeist\NeosGuidelines\Validators\Package\FusionValidator
          options:
            excludedFileNames: ['Root.fusion', 'Shame.fusion']
            allowedFusionPrefixes: ['Content', 'Document', 'Prototype', 'Component']